### PR TITLE
feat: Update `postProcess` config to allow alternate save mechanism

### PR DESCRIPTION
**Pull request by danielsharvey**
~~A new `saveSwagger()` configuration function allows an alternate
mechanism for saving the generated Swagger to be specified, rather
than the standard writing a file to the filesystem.~~

Update `postProcess` configuration to run after tag clean-up phase
to allow an alternate mechanism for saving the generated Swagger to
be specified, rather than the standard writing a file to the filesystem.

Allow `swaggerJsonPath` to be empty/null/undefined, in which case
no file write attempted.

This supports deployment to environments that do not allow writing to the
filesystem e.g. store in memory or database.

### CODE REVIEW

**Comment by danielsharvey** [comment]
For easy reference: https://travis-ci.org/github/theoomoregbee/sails-hook-swagger-generator/builds/726570799

**Comment by theoomoregbee** [comment]
just fixed the Travis CI bug: https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2 

restarted the build to see if it will show up here

**Review by theoomoregbee — APPROVED** [review]
👍

**Review by theoomoregbee — COMMENTED** [review]
since no big difference between this and `postProcess` method, what about we lean towards encouraging the use of that and keep the ignore saving to local storage when `swaggerJsonPath` is not truthy

**Comment by danielsharvey** [comment]
Let’s go that way. I could not make up my mind given the small amount of post-processing (tag clean-up) that currently happens after `postProcess` is called.

I had originally left tag cleanup after `postProcess` to allow that method to reference tags before cleanup occurs. If we utilise `postProcess` it probably makes sense to move cleanup before it is called to ensure consistency between between the two save methods.

**Pull request merged**
