### PR TITLE
feat: clean up for #44 support with sails v1.0, open api v3 and jsDoc swagger doc also Switch project to typescript

### PR DESCRIPTION
**Pull request by theoomoregbee**
### TODO
- [x] Switch project to ts for easier understanding of what is going on and for maintenance sake.
- [x] update readme for breaking change and also updates on how we pick up swagger documentation 

#### #44 TODO
- Clean up parsers
	- [x] parse model test
	- [x] parse model 
	- [x] parse all/custom routes test
	- [x] parse all/custom routes
	- [x] merge routes(all/custom)
	- [x] load swagger doc from controller or actions (ongoing)
		- [x] parse and test controllers
		- [x] parse and test action files 
- Clean up generators
	- [x] attribute schema
	- [x] model schemas
	- [X] paths
	- [x] model schemas test
	- [ ] ~paths test (will do this when we break down the `generatePaths` function~

- General cleanup
	- consolidate swagger components and tags in
		- [x] Models (model override controllers)
		- [x] Controllers (controller override action2)
		- [x] Action2 

* This removes the js doc swagger doc from routes.js and now it only checks for swagger js doc in
	* [x] controller
	* [x] standalone
	* [x] model

Closes #44  in favor of this (when all the todos are done)

### CODE REVIEW

**Comment by davidkregl** [comment]
Hello @theo4u, 

I can't wait for this to be released. Can I somehow put a hand to work? Maintaining documentation in Postman manually is a real pain in the ass.

Thanks!

**Comment by theo4u** [comment]
Thanks @davidkregl, you can assist by adding/converting the `generator.js` to `generator.ts` and adding test respectively. 

This should be in a week plus, trying to find pocket time to work on this.

**Comment by davidkregl** [comment]
> Thanks @davidkregl, you can assist by adding/converting the `generator.js` to `generator.ts` and adding test respectively.
> 
> This should be in a week plus, trying to find pocket time to work on this.

Sorry for the late reply. I do not have any experience with TypeScript. On the other hand, do you think with a bit of research and a linter I will be able to do it?

**Comment by theoomoregbee** [comment]
openapiv3

**Comment by danielsharvey** [comment]
Looks good! Apologies I've not had time to contribute to the typescript work yet. I also have a few more changes to push, but happy to do that to the upgrade typescript version. 

In particular, I realised that (whilst not clearly documented), Sails recommends the used of the `meta` field in attributes which I am proposing to use to contain additional OpenAPI/Swagger docs for individual attributes. 

How much more to do?

**Comment by theoomoregbee** [comment]
Left with updating the readme and consolidating the tags and components from models, controllers, and action2. Will add you as reviewer once I push the last piece. Might help out maybe breaking down the `generatePaths` function later.

> In particular, I realised that (whilst not clearly documented), Sails recommends the used of the meta field in attributes which I am proposing to use to contain additional OpenAPI/Swagger docs for individual attributes.

nice

**Comment by theoomoregbee** [comment]
@danielsharvey updated the readme, removed the `config.routes.js` swagger doc documentation and also revamping the way the `.swagger` object works for `models/controllers/actions2/config.routes.js`. 

**You can give it a look when you are free if it's working as expected**, was unable to add a detailed test for `generateSchema` because of my limited knowledge on sails migrations. Added a very minor test just to check if it's converting the schema to the acceptable OpenAPIV3 format.

**Comment by danielsharvey** [comment]
@theoomoregbee Interim update: I'm working through this and it looks good.
 
Some comments so far:
1. Your cleanup of `actions`, `tags`, `components` rather than my "underscore" varieties makes good sense.
2. I’ve done more work since submitting my original PR on the duplicates in `router:bind` events (middleware related) and am adjusted the parsing to account for this.
3. When aggregating routes, I also realised that I was assuming the only blueprint routes are the implicit (shadow) routes. However, `config/routes.js` may reference blueprint actions on other routes. I'm recommending some changes to allow for this.
3. Whilst not recommended for PROD, we should support [shortcut blueprint routes](https://sailsjs.com/documentation/concepts/blueprints/blueprint-routes#?shortcut-blueprint-routes).

Hoping to get done on the weekend.

**Comment by theoomoregbee** [comment]
> I’ve done more work since submitting my original PR on the duplicates in router:bind events (middleware related) and am adjusted the parsing to account for this.

I observed it and I did this https://github.com/theoomoregbee/sails-hook-swagger-generator/blob/5d64b63a61bfa8ee6da92012646438e5645d7d56/index.ts#L37-L45 (maybe it's not covering all the cases)

I will merge this in and release it as breaking change today. 

> Hoping to get done on the weekend. 

thanks

**Pull request merged**
